# Generated by Django 5.2.4 on 2025-07-03 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(max_length=20)),
                ('booth_name', models.CharField(max_length=100)),
                ('building_name', models.CharField(max_length=100)),
                ('duration', models.CharField(default='7 AM - 7 PM', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.CharField(max_length=10, unique=True)),
                ('ward_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('polling_officer', 'Polling Officer'), ('assistant_polling_officer', 'Assistant Polling Officer'), ('security_officer', 'Security Officer'), ('technical_officer', 'Technical Officer')], max_length=50)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.booth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.office')),
            ],
        ),
        migrations.AddField(
            model_name='booth',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.ward'),
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('place_name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='location_updates/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('employee', 'serial_number')},
            },
        ),
    ]
