# Generated by Django 5.2.4 on 2025-07-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_booth_ward_remove_employee_booth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
