# Generated by Django 5.2.4 on 2025-07-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_name_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationupdate',
            name='image',
        ),
        migrations.AddField(
            model_name='locationupdate',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL link to the uploaded image', max_length=500, null=True),
        ),
    ]
